### ISSUE TITLE
todos for MVP

### ISSUE THREAD

**Issue by thesayyn** [chainguard-dev/rules_apko#4]
```[tasklist]
### Tasks
- [x] Do https://github.com/chainguard-dev/rules_apko/pull/1#discussion_r1326570439
- [x] Document attributes https://github.com/chainguard-dev/rules_apko/pull/10
- [x] Document translate_lock https://github.com/chainguard-dev/rules_apko/pull/10
- [x] Warn users about when initial setup hasn't been done #9
- [x] Document how to generate lock.json file
- [x] Publish to BCR
- [x] Currently, binaries are downloaded from https://github.com/thesayyn/apko/releases/tag/v0.0.0 due to lack of a recent release for apko. Binaries should be fetched from apko instead.
```
